import { Complaint, ComplaintStatus, ComplaintCategory, Sentiment, DataSource } from './types';

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: 'C001',
    source: DataSource.Twitter,
    username: '@PriyaSharma',
    location: 'Bandra, Mumbai',
    complaint_text: 'Massive pothole on Linking Road near the signal. It caused a huge traffic jam this morning!',
    timestamp: '2024-07-29T10:30:00Z',
    status: ComplaintStatus.Pending,
    assigned_authority: 'BMC Public Works',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.Infrastructure,
  },
  {
    id: 'C002',
    source: DataSource.MunicipalPortal,
    username: 'Rajesh Kumar',
    location: 'Koramangala, Bangalore',
    complaint_text: 'Garbage has not been collected in 5th Block for 3 days. The bins are overflowing and the smell is unbearable.',
    timestamp: '2024-07-29T09:45:00Z',
    status: ComplaintStatus.InReview,
    assigned_authority: 'BBMP Sanitation',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.Sanitation,
  },
  {
    id: 'C003',
    source: DataSource.Reddit,
    username: 'u/Delhiite',
    location: 'Saket, New Delhi',
    complaint_text: 'Streetlight on the main road of PVR Anupam complex has been out for a week. It feels very unsafe at night.',
    timestamp: '2024-07-28T22:15:00Z',
    status: ComplaintStatus.Resolved,
    assigned_authority: 'MCD Electricity Wing',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.Safety,
  },
  {
    id: 'C004',
    source: DataSource.CommunityForum,
    username: 'AnjaliRao',
    location: 'T. Nagar, Chennai',
    complaint_text: 'The MTC bus route 29C is consistently late by 20-30 minutes. Thousands of us depend on it for our daily commute.',
    timestamp: '2024-07-28T08:00:00Z',
    status: ComplaintStatus.InReview,
    assigned_authority: 'Chennai Transport Corp.',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.PublicTransport,
  },
  {
    id: 'C005',
    source: DataSource.Twitter,
    username: '@ParkLoverHyd',
    location: 'Jubilee Hills, Hyderabad',
    complaint_text: 'The swings in KBR Park are broken and rusty. This is dangerous for the children playing there.',
    timestamp: '2024-07-27T14:00:00Z',
    status: ComplaintStatus.Pending,
    assigned_authority: 'GHMC Parks Dept.',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.Parks,
  },
  {
    id: 'C006',
    source: DataSource.MunicipalPortal,
    username: 'VikramSingh',
    location: 'Sector V, Kolkata',
    complaint_text: 'Loud construction noise from the new IT building continues past midnight. This is a residential area!',
    timestamp: '2024-07-27T23:30:00Z',
    status: ComplaintStatus.Pending,
    assigned_authority: 'Kolkata Police',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.Noise,
  },
  {
    id: 'C007',
    source: DataSource.Reddit,
    username: 'u/PuneCyclist',
    location: 'FC Road, Pune',
    complaint_text: 'The bike lane on Fergusson College Road is always blocked by parked cars. It is completely useless.',
    timestamp: '2024-07-26T17:00:00Z',
    status: ComplaintStatus.InReview,
    assigned_authority: 'Pune Traffic Police',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.Infrastructure,
  },
  {
    id: 'C008',
    source: DataSource.Twitter,
    username: '@CleanJaipur',
    location: 'C-Scheme, Jaipur',
    complaint_text: 'Illegal dumping of construction debris in the alley behind my house. Needs to be cleared immediately.',
    timestamp: '2024-07-26T11:20:00Z',
    status: ComplaintStatus.Resolved,
    assigned_authority: 'Jaipur Municipal Corp.',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.Sanitation,
  },
    {
    id: 'C015',
    source: DataSource.CommunityForum,
    username: 'ConcernedParent',
    location: 'Indiranagar, Bangalore',
    complaint_text: 'Cars are speeding near the National Public School. We urgently need speed breakers before an accident happens.',
    timestamp: '2024-07-29T15:30:00Z',
    status: ComplaintStatus.Pending,
    assigned_authority: 'Bangalore Traffic Police',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.Safety,
  },
  {
    id: 'C016',
    source: DataSource.Reddit,
    username: 'u/WaterWoes',
    location: 'Velachery, Chennai',
    complaint_text: 'Irregular water supply for the past 4 days. We are having to buy expensive water tankers.',
    timestamp: '2024-07-30T11:00:00Z',
    status: ComplaintStatus.Pending,
    assigned_authority: 'Chennai Metro Water',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.Sanitation,
  },
  {
    id: 'C017',
    source: DataSource.Twitter,
    username: '@HappyCommuter',
    location: 'Cyber Hub, Gurgaon',
    complaint_text: 'The new underpass has really improved the traffic flow. Great work by @GMDA!',
    timestamp: '2024-07-30T13:00:00Z',
    status: ComplaintStatus.Resolved,
    assigned_authority: 'GMDA',
    sentiment: Sentiment.Positive,
    category: ComplaintCategory.Infrastructure,
  }
];

export const NEW_MOCK_COMPLAINTS_TO_ADD: Complaint[] = [
  {
    id: 'C018',
    source: DataSource.Twitter,
    username: '@MumbaiTraffic',
    location: 'Dadar, Mumbai',
    complaint_text: 'The traffic signal at Dadar Circle is not working. Causing complete chaos.',
    timestamp: new Date().toISOString(),
    status: ComplaintStatus.Pending,
    assigned_authority: 'Mumbai Traffic Police',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.PublicTransport,
  },
  {
    id: 'C019',
    source: DataSource.Reddit,
    username: 'u/BangaloreGardens',
    location: 'Lalbagh, Bangalore',
    complaint_text: 'The beautiful flower beds are overgrown with weeds. The park needs better maintenance.',
    timestamp: new Date().toISOString(),
    status: ComplaintStatus.Pending,
    assigned_authority: 'BBMP Parks Dept.',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.Parks,
  },
  {
    id: 'C020',
    source: DataSource.Twitter,
    username: '@QuietKolkata',
    location: 'Park Street, Kolkata',
    complaint_text: 'Loud music from restaurants after 11 PM every single night. We are unable to sleep.',
    timestamp: new Date().toISOString(),
    status: ComplaintStatus.Pending,
    assigned_authority: 'Kolkata Police',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.Noise,
  },
  {
    id: 'C021',
    source: DataSource.CommunityForum,
    username: 'AshaN',
    location: 'Ameerpet, Hyderabad',
    complaint_text: 'The metro station escalator is not working for the past 2 weeks. It is very difficult for senior citizens.',
    timestamp: new Date().toISOString(),
    status: ComplaintStatus.Pending,
    assigned_authority: 'Hyderabad Metro Rail',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.Infrastructure,
  },
  {
    id: 'C022',
    source: DataSource.MunicipalPortal,
    username: 'SunilG',
    location: 'Rohini, New Delhi',
    complaint_text: 'The storm water drain is choked with plastic and garbage. With monsoon here, our street will definitely flood.',
    timestamp: new Date().toISOString(),
    status: ComplaintStatus.Pending,
    assigned_authority: 'MCD Sanitation',
    sentiment: Sentiment.Negative,
    category: ComplaintCategory.Sanitation,
  }
];